#! /bin/bash

PORT1='/tmp/ttyS1'
PORT2='/tmp/ttyS2'

echo Connecting port $PORT1
echo Connecting port $PORT2

socat -d -d PTY,link=$PORT1,echo=0 PTY,link=$PORT2,echo=0 &

echo Connected port $PORT1
echo Connected port $PORT2